<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(PenbanNetVersion)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Penban.Models\Penban.Models.csproj" />
    <ProjectReference Include="..\Penban.Services.Abstractions\Penban.Services.Abstractions.csproj" />
    <ProjectReference Include="..\Penban.Data\Penban.Data.csproj" />
    <ProjectReference Include="..\Penban.Util\Penban.Util.csproj" />
  </ItemGroup>

</Project>
